version: '3.8'

services:

  postgres:
    container_name: pokedex_postgres
    image: postgres:15.3-alpine3.18
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:${POSTGRES_PORT}
